services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:3000:3000"
    env_file: .env
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - storage:/rails/storage
    stdin_open: true
    tty: true

volumes:
  storage:
